// Auto-generated by GeNYG Native
import * as extraActions from "../extra-actions";

import * as ui from "./ui";

export const reducers = {
  ui: ui.uiStore.reducer,
};

export const actions = {
  ...extraActions,
  ...ui.uiStore.actions,
};

export const selectors = {
  ...ui.selectors,
};

export const sagas = [
  ...Object.values(ui.sagas),
];
