// Auto-generated by GeNYG Native test-app
import * as extraActions from "../extra-actions";

import * as ui from "./ui";
import * as ajax from "./ajax";
import * as feedback from "./feedback";
import * as counter from "./counter";
import * as contacts from "./contacts";
import * as posts from "./posts";

export const reducers = {
  ui: ui.uiStore.reducer,
  ajax: ajax.ajaxStore.reducer,
  feedback: feedback.feedbackStore.reducer,
  counter: counter.counterStore.reducer,
  contacts: contacts.contactsStore.reducer,
  posts: posts.postsStore.reducer,
};

export const actions = {
  ...extraActions,
  ...ui.uiStore.actions,
  ...ajax.ajaxStore.actions,
  ...feedback.feedbackStore.actions,
  ...counter.counterStore.actions,
  ...contacts.contactsStore.actions,
  ...posts.postsStore.actions,
};

export const selectors = {
  ...ui.selectors,
  ...ajax.selectors,
  ...feedback.selectors,
  ...counter.selectors,
  ...contacts.selectors,
  ...posts.selectors,
};

export const sagas = [
  ...Object.values(ui.sagas),
  ...Object.values(ajax.sagas),
  ...Object.values(feedback.sagas),
  ...Object.values(counter.sagas),
  ...Object.values(contacts.sagas),
  ...Object.values(posts.sagas),
];
