import Generator from "yeoman-generator";
import chalk from "chalk";
import yosay from "yosay";
import path from "path";
import { pascalCase } from "pascal-case";
import { requirePackages } from "../../common/index.js";

export default class SliceGenerator extends Generator {
  async prompting() {
    requirePackages(this, ["redux"]);

    this.log(
      yosay(
        `Welcome to ${chalk.red(
          "GeNYG Native",
        )} redux slice generator. Follow the quick configuration to create a new slice!`,
      ),
    );

    const answers = await this.prompt([
      {
        type: "input",
        name: "sliceName",
        message: "What is your slice name?",
        validate: (v) => !!(v && v.trim()) || "Please enter a slice name",
        filter: (v) => (v || "").trim(),
      },
      {
        type: "confirm",
        name: "useSagas",
        message: "Would you like to create a saga file?",
        default: true,
      },
    ]);

    if (!answers.sliceName) {
      this.log(yosay(chalk.red("Please give your slice a name next time!")));
      this.abort = true;
      return;
    }

    this.answers = answers;
  }

  writing() {
    if (this.abort) return;

    const { useSagas, sliceName } = this.answers;
    const pCsliceName = pascalCase(sliceName);
    const reduxStorePath = "src/redux-store";

    // Slice index.ts
    this.fs.copyTpl(
      this.templatePath("index.ejs"),
      this.destinationPath(
        path.posix.join(reduxStorePath, "slices", sliceName, "index.ts"),
      ),
      { sliceName, pCsliceName, useSagas },
    );

    // Slice interfaces
    this.fs.copyTpl(
      this.templatePath("interface.index.ejs"),
      this.destinationPath(
        path.posix.join(
          reduxStorePath,
          "slices",
          sliceName,
          `${sliceName}.interfaces.ts`,
        ),
      ),
      { pCsliceName },
    );

    // Slice selectors
    this.fs.copyTpl(
      this.templatePath("selectors.index.ejs"),
      this.destinationPath(
        path.posix.join(
          reduxStorePath,
          "slices",
          sliceName,
          `${sliceName}.selectors.ts`,
        ),
      ),
      { sliceName, pCsliceName },
    );

    // Slice sagas (optional)
    if (useSagas) {
      this.fs.copyTpl(
        this.templatePath("sagas.index.ejs"),
        this.destinationPath(
          path.posix.join(
            reduxStorePath,
            "slices",
            sliceName,
            `${sliceName}.sagas.ts`,
          ),
        ),
        { sliceName },
      );
    }

    // Update slices/index.ts
    const indexPath = this.destinationPath(
      path.posix.join(reduxStorePath, "slices", "index.ts"),
    );

    let slicesIndex = "";
    try {
      slicesIndex = this.fs.read(indexPath);
    } catch (e) {
      this.log(
        chalk.yellow(
          `Warning: slices index not found at ${indexPath}. Creating a new one.`,
        ),
      );
      slicesIndex =
        "// Auto-generated by GeNYG Native\n\nimport { combineReducers } from '@reduxjs/toolkit';\n\nexport const reducers = {\n};\n\nexport const actions = {\n};\n\nexport const selectors = {\n};\n\nexport const sagas = [\n];\n";
    }

    // 1) add import line
    try {
      const importMatch = slicesIndex.match(/import(.*?);\r?\n\r?\n/)[0];
      slicesIndex = slicesIndex.replace(
        importMatch,
        `${importMatch.slice(0, -1)}import * as ${sliceName} from "./${sliceName}";\n\n`,
      );
    } catch (e) {
      this.log(
        chalk.yellow(
          `Warning: could not inject import for slice '${sliceName}'. Please update slices/index.ts manually.`,
        ),
      );
    }

    // 2) add reducer entry
    try {
      const reducerMatch = slicesIndex.match(
        /(.*)Store(.*?).reducer,?\r?\n}/,
      )[0];
      slicesIndex = slicesIndex.replace(
        reducerMatch,
        `${reducerMatch.slice(0, -1)}  ${sliceName}: ${sliceName}.${sliceName}Store.reducer,\n}`,
      );
    } catch (e) {
      this.log(
        chalk.yellow(
          `Warning: could not inject reducer for slice '${sliceName}'.`,
        ),
      );
    }

    // 3) add actions spread
    try {
      const actionsMatch = slicesIndex.match(
        /(.*)Store(.*?).actions,?\r?\n}/,
      )[0];
      slicesIndex = slicesIndex.replace(
        actionsMatch,
        `${actionsMatch.slice(0, -1)}  ...${sliceName}.${sliceName}Store.actions,\n}`,
      );
    } catch (e) {
      this.log(
        chalk.yellow(
          `Warning: could not inject actions for slice '${sliceName}'.`,
        ),
      );
    }

    // 4) add selectors spread
    try {
      const selectorsMatch = slicesIndex.match(/(.*).selectors,?\r?\n}/)[0];
      slicesIndex = slicesIndex.replace(
        selectorsMatch,
        `${selectorsMatch.slice(0, -1)}  ...${sliceName}.selectors,\n}`,
      );
    } catch (e) {
      this.log(
        chalk.yellow(
          `Warning: could not inject selectors for slice '${sliceName}'.`,
        ),
      );
    }

    // 5) add sagas if present
    if (useSagas) {
      try {
        const sagasMatch = slicesIndex.match(
          /(.*)Object.values(.*),?\r?\n]/,
        )[0];
        slicesIndex = slicesIndex.replace(
          sagasMatch,
          `${sagasMatch.slice(0, -1)}  ...Object.values(${sliceName}.sagas),\n]`,
        );
      } catch (e) {
        this.log(
          chalk.yellow(
            `Warning: could not inject sagas for slice '${sliceName}'.`,
          ),
        );
      }
    }

    this.fs.write(indexPath, slicesIndex);
  }
}
